name: Report Test exceptions

# on:
#   pull_request:
#     types: [ closed ]
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK:
        required: true
      DATADOG_API_KEY:
        required: true

jobs:
  get-labels:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      labels: ${{ steps.pr-labels.outputs.labels }}
      size: ${{ steps.pr-size.outputs.size }}
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      - name: Get size label
        id: pr-size
        run: |
          if [ -n "$GITHUB_PR_LABEL_SIZE_XS" ]; then
            echo "::set-output name=size::xs"
          elif [ -n "$GITHUB_PR_LABEL_SIZE_S" ]; then
            echo "::set-output name=size::s"
          elif [ -n "$GITHUB_PR_LABEL_SIZE_M" ]; then
            echo "::set-output name=size::m"
          elif [ -n "$GITHUB_PR_LABEL_SIZE_L" ]; then
            echo "::set-output name=size::l"
          elif [ -n "$GITHUB_PR_LABEL_SIZE_XL" ]; then
            echo "::set-output name=size::xl"
          elif [ -n "$GITHUB_PR_LABEL_SIZE_XXL" ]; then
            echo "::set-output name=size::xxl"
          else
            echo "::set-output name=size::na"
          fi

  report-test-exceptions:
    needs: [get-labels]
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(needs.get-labels.outputs.labels, ' tests-not-required ')
    steps:
      - name: Get PR URL
        id: pr-url
        uses: ammaratef45/pr-url-action@v1

      - name: Report to slack if contains label
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Psst! Someone invoked EXCEPTION TO TESTS
          SLACK_MESSAGE: "Test writing is skipped! Here's the PR ${{ steps.pr-url.outputs.url }}. Please explain why tests are not written for this PR."
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: why-no-tests
          SLACK_USERNAME: github-actions
          SLACK_COLOR: "#2874a7"
          SLACK_ICON_EMOJI: ":rotating_light:"

      - name: Store metrics for exception cases
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics: |
            - type: "count"
              name: "test.enforcement.pr.exception.count"
              value: 1.0
              host: ${{ github.repository_owner }}
              tags:
                - "repo_name:${{ github.repository }}"
                - "merged_by:${{ github.actor }}"
                - "size:${{ needs.get-labels.outputs.size }}"

  report-test-compliance:
    needs: [get-labels]
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && !contains(needs.get-labels.outputs.labels, ' tests-not-required ')
    steps:
      - name: Store metrics for compliant cases
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics: |
            - type: "count"
              name: "test.enforcement.pr.compliant.count"
              value: 1.0
              host: ${{ github.repository_owner }}
              tags:
                - "repo_name:${{ github.repository }}"
                - "merged_by:${{ github.actor }}"
                - "size:${{ needs.get-labels.outputs.size }}"
