name: Enforce Tests for PR (to be deleted after testing)

on:
  pull_request:
    types: [ closed ]

jobs:
  report-test-exceptions:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2

      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

      - name: Get PR URL
        id: pr-url
        uses: ammaratef45/pr-url-action@v1

      - name: Report to slack if contains label
        if: contains(steps.pr-labels.outputs.labels, ' test-not-required ')
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: Psst! Someone invoked EXCEPTION TO TESTS
          SLACK_MESSAGE: "Test writing is skipped! Here's the PR ${{ steps.pr-url.outputs.url }}. Please explain why tests are not written for this PR."
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: test-popo
          SLACK_USERNAME: github-actions
          SLACK_COLOR: "#2874a7"
          SLACK_ICON_EMOJI: ":rotating_light:"

      - name: Get size label
        id: pr-size
        run: |
          if [ -n "$GITHUB_PR_LABEL_SIZE_XS" ]; then
            echo "::set-output name=size::xs"
          elif [ -n "$GITHUB_PR_LABEL_SIZE_S" ]; then
            echo "::set-output name=size::s"
          elif [ -n "$GITHUB_PR_LABEL_SIZE_M" ]; then
            echo "::set-output name=size::m"
          elif [ -n "$GITHUB_PR_LABEL_SIZE_L" ]; then
            echo "::set-output name=size::l"
          elif [ -n "$GITHUB_PR_LABEL_SIZE_XL" ]; then
            echo "::set-output name=size::xl"
          elif [ -n "$GITHUB_PR_LABEL_SIZE_XXL" ]; then
            echo "::set-output name=size::xxl"
          else
            echo "::set-output name=size::na"
          fi

      - name: Store metrics for exception cases
        if: contains(steps.pr-labels.outputs.labels, ' test-not-required ')
        uses: masci/datadog@v1
        with:
          api-key: ${{ secrets.DATADOG_API_KEY }}
          metrics: |
            - type: "count"
              name: "test.enforcement.pr.exception.count"
              value: 1.0
              host: ${{ github.repository_owner }}
              tags:
                - "repo_name:${{ github.repository }}"
                - "merged_by:${{ github.actor }}"
      #           - "size:${{ steps.pr-size.outputs.size }}"
      #
      # - name: Store metrics for compliant cases
      #   if: !contains(steps.pr-labels.outputs.labels, ' test-not-required ')
      #   uses: masci/datadog@v1
      #   with:
      #     api-key: ${{ secrets.DATADOG_API_KEY }}
      #     metrics: |
      #       - type: "count"
      #         name: "test.enforcement.pr.compliance.count"
      #         value: 1.0
      #         host: ${{ github.repository_owner }}
      #         tags:
      #           - "repo_name:${{ github.repository }}"
      #           - "merged_by:${{ github.actor }}"
      #           - "size:${{ steps.pr-size.outputs.size }}"
