name: Enforce Tests for PR

# on:
#   pull_request:
#     types: [ labeled, synchronize ]
on:
  workflow_call:

#Pass test if there is a label
jobs:
  enforce-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Check for tests"
        uses: brettcannon/check-for-changed-files@v1
        with:
          file-pattern: |
            tests/*.py
            tests/**/*.py
          skip-label: "tests not required"
          failure-message: "Missing a tests in $file-pattern; please add at least one or apply the $skip-label label to the pull request"
