name: Enforce Tests for PR

# on:
#   pull_request:
#     types: [ labeled, synchronize ]
on:
  workflow_call:

#Pass test if there is a label
jobs:
  get-label:
    runs-on: ubuntu-latest
    outputs:
      pr-labels: ${{ steps.pr-labels.outputs.labels }}
    steps:
      - name: Get PR labels
        id: pr-labels
        uses: joerick/pr-labels-action@v1.0.6

  enforce-test:
    needs: [get-label]
    runs-on: ubuntu-latest
    # if: !contains(needs.get-label.outputs.pr-labels, ' tests-not-required ')
    steps:
      - name: Get Changed Files
        id: files
        uses: jitterbit/get-changed-files@v1

      - name: Check for tests manual
        if: $ {{ !contains(needs.get-label.outputs.pr-labels, ' tests-not-required ') }}
        run: |
          file-pattern='tests/.*/*.py'
          for changed_file in ${{ steps.files.outputs.all }}; do
            if [[ "$changed_file" =~ "$file-pattern" ]]; then
              exit 0
            fi
          done
          echo "Missing a tests in $file-pattern; Please add at least one test or apply the tests not required label to the pull request"
          exit 1

      - name: Check for tests
        uses: brettcannon/check-for-changed-files@v1
        with:
          file-pattern: |
            tests/*.py
            tests/**/*.py
          skip-label: "tests not required"
          failure-message: "Missing a tests in $file-pattern; please add at least one or apply the $skip-label label to the pull request"
